version: '3'
services:

  web:
    image: "hub.egistic.kz/nginx:latest"
    restart: "always"
    expose:
      - "80"
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
      - "PROXY_PASS=http://app:8080"
    networks:
      - "geoserver"
    volumes:
      - "../nginx/conf.d:/etc/nginx/conf.d/templates"
    labels:
      - "traefik.frontend.rule=Host:${DOMAIN_NAME}"
    command: /bin/bash -c "envsubst '$${DOMAIN_NAME} $${PROXY_PASS}' < /etc/nginx/conf.d/templates/geoserver.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  app:
    container_name: "geoserver"
    restart: "always"
    hostname: "geoserver"
    image: "thinkwhere/geoserver:2.14"
    expose:
      - "8080"
    environment:
      - "GEOSERVER_LOG_LOCATION=/opt/geoserver/data_dir/logs/geoserver.log"
    volumes:
      - "tomcat:/usr/local/tomcat"
      - "data:/opt/geoserver/data_dir"
      - "rasters:/root/Rasters"
      - "./web.xml:/usr/local/tomcat/conf/web.xml"
#      - "./plugins:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib"
    networks:
      - "geoserver"
      - "postgis"
    labels:
      - "traefik.backend=geoserver"

networks:
  geoserver:
    external:
      name: "geoserver"
  postgis:
    external:
      name: "postgis"

volumes:
  data:
    external: false
  rasters: 
    external: true
  tomcat:
    external: false
